name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        uses: Sacsam005/blog-post-workflow@master
        with:
          feed_list: "https://shachinmagar120sm.wixsite.com/codingproficiency/blog-feed.xml"
